# Generated by Django 5.2.8 on 2025-11-29 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус')),
                ('text', models.TextField(max_length=250, verbose_name='Текст вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_or_wrong', models.BooleanField(choices=[(0, 'Неверный'), (1, 'Верный')], default=0, verbose_name='Верный ли ответ?')),
                ('text', models.TextField(max_length=150, verbose_name='Текст ответа')),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers_set', to='quiz.questions', verbose_name='Ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя викторины')),
                ('published', models.CharField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус')),
                ('questions', models.ManyToManyField(related_name='quizes', to='quiz.questions', verbose_name='Вопросы')),
            ],
        ),
    ]
