# Generated by Django 5.2.8 on 2025-12-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quizes_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.TextField(max_length=250, unique=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя викторины'),
        ),
    ]
